import type { Metadata } from "next";
import "@/assets/styles/globals.css";

type mainLayoutPropsType = Readonly<{ children: React.ReactNode }>;

export const metadata: Metadata = {
  title: "Create Next App", // TODO: Change the title when I think of a name for the app
  description: "Generated by create next app", // TODO: Change the description later
};

const MainLayout = ({ children }: mainLayoutPropsType) => {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
};

export default MainLayout;
